# Generated by Django 2.2.4 on 2023-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='movie_description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default='1990-1-1'),
            preserve_default=False,
        ),
    ]
