# Generated by Django 2.2.4 on 2023-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='first_name',
            field=models.CharField(default='secret', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(default='another_secret', max_length=255),
            preserve_default=False,
        ),
    ]
