# Generated by Django 2.2.4 on 2023-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='desc',
            field=models.CharField(default='description about this book', max_length=255),
            preserve_default=False,
        ),
    ]
